bug: Cannot bind argument to parameter 'Base' because it is an empty string

diff --git a/eng/pipelines/templates/steps/sync-repo-files.yml b/eng/pipelines/templates/steps/sync-repo-files.yml
--- a/eng/pipelines/templates/steps/sync-repo-files.yml
+++ b/eng/pipelines/templates/steps/sync-repo-files.yml
@@ -16,157 +16,160 @@ parameters:
     type: string
 
 steps:
-- pwsh: |
-   Install-Module -Name PowerShellForGitHub -Force
-  displayName: Install PowerShellForGitHub
-
-- ${{ each repo in parameters.Repos }}:
   - pwsh: |
-      Set-PsDebug -Trace 1
-      $SourceRepo = '${{ repo.key }}'
-      $SourceFolder = $SourceRepo -split "/" -join "-"
-      $SourceBranch = '${{ repo.value.Branch }}'
-      if (-not (Test-Path ${{ repo.key }})) {
-        New-Item -Path $SourceFolder -ItemType Directory -Force
-        Set-Location $SourceFolder
-        git init
-        git remote add Source "https://${{ parameters.GH_TOKEN }}@github.com/${SourceRepo}.git"
-      } else {
-        Set-Location $SourceFolder
-      }
+      Install-Module -Name PowerShellForGitHub -Force
+    displayName: Install PowerShellForGitHub
 
-      # Check the default branch
-      if (!$SourceBranch) {
-        $defaultBranch = (git remote show Source | Out-String) -replace "(?ms).*HEAD branch: (\w+).*", '$1'
-        Write-Host "No source branch. Fetch default branch $defaultBranch."
-        $SourceBranch = $defaultBranch
-      }
+  - ${{ each repo in parameters.Repos }}:
+      - pwsh: |
+          Set-PsDebug -Trace 1
+          $SourceRepo = '${{ repo.key }}'
+          $SourceFolder = $SourceRepo -split "/" -join "-"
+          $SourceBranch = '${{ repo.value.Branch }}'
+          if (-not (Test-Path ${{ repo.key }})) {
+            New-Item -Path $SourceFolder -ItemType Directory -Force
+            Set-Location $SourceFolder
+            git init
+            git remote add Source "https://${{ parameters.GH_TOKEN }}@github.com/${SourceRepo}.git"
+          } else {
+            Set-Location $SourceFolder
+          }
 
-      git fetch --no-tags Source $SourceBranch
-      if ($LASTEXITCODE -ne 0) {
-        Write-Host "#`#vso[task.logissue type=error]Failed to fetch ${SourceRepo}:${SourceBranch}"
-        exit 1
-      }
+          # Check the default branch
+          if (!$SourceBranch) {
+            $defaultBranch = (git remote show Source | Out-String) -replace "(?ms).*HEAD branch: (\w+).*", '$1'
+            Write-Host "No source branch. Fetch default branch $defaultBranch."
+            $SourceBranch = $defaultBranch
+          }
 
-      git checkout -B source_branch "refs/remotes/Source/${SourceBranch}"
-
-      Set-PsDebug -Off
-
-    displayName: ${{ repo.key }} - Clone ${{ repo.value.Branch }}
-    continueOnError: true
-
-  - ${{ each target in repo.value.TargetRepos }}:
-    - pwsh: |
-        Set-PsDebug -Trace 1
-        $UserName = "azure-sdk"
-        $UserEmail = "azuresdk@microsoft.com"
-
-        $home_dir = $pwd
-
-        $SourceRepo = '${{ repo.key }}'
-        $SourceFolder = $SourceRepo -split "/" -join "-"
-        $SourceSyncFilePath = '${{repo.value.Path}}'
-        $SourceBranch = '${{ repo.value.Branch }}'
-
-        $TargetRepo = '${{ target.key }}'
-        $TargetFolder = $TargetRepo -split "/" -join "-"
-        $TargetSyncFilePath = '${{target.value.Path}}'
-        $TargetBranch = '${{ target.value.Branch }}'
-
-        Function FailOnError([string]$ErrorMessage, $CleanUpScripts = 0) {
+          git fetch --no-tags Source $SourceBranch
           if ($LASTEXITCODE -ne 0) {
-            Write-Host "#`#vso[task.logissue type=error]$ErrorMessage"
-            if ($CleanUpScripts -ne 0) { Invoke-Command $CleanUpScripts }
+            Write-Host "#`#vso[task.logissue type=error]Failed to fetch ${SourceRepo}:${SourceBranch}"
             exit 1
           }
-        }
 
-        if (-not (Test-Path $TargetFolder)) {
-          New-Item -Path $TargetFolder -ItemType Directory -Force
-          Set-Location $TargetFolder
-          git init
-          git remote add Target "https://${{parameters.GH_TOKEN}}@github.com/${TargetRepo}.git"
-        } else {
-          Set-Location $TargetFolder
-        }
+          git checkout -B source_branch "refs/remotes/Source/${SourceBranch}"
 
-        if (!$TargetBranch) {
-          $defaultBranch = (git remote show Target | Out-String) -replace "(?ms).*HEAD branch: (\w+).*", '$1'
-          Write-Host "No target branch. Fetch default branch $defaultBranch."
-        }
+          Set-PsDebug -Off
 
-        git fetch --all
-        FailOnError "Failed to fetch DefaultBranch ${defaultBranch}."
+        displayName: ${{ repo.key }} - Clone ${{ repo.value.Branch }}
+        continueOnError: true
 
-        $isExistBranch = $(git branch --list --remotes "Target/$TargetBranch")
-        if ($isExistBranch) {
-          git checkout -b $TargetBranch "Target/$TargetBranch"
-        }
-        else {
-          git checkout -b $TargetBranch "Target/$defaultBranch"
-        }
+      - ${{ each target in repo.value.TargetRepos }}:
+          - pwsh: |
+              Set-PsDebug -Trace 1
+              $UserName = "azure-sdk"
+              $UserEmail = "azuresdk@microsoft.com"
 
-        if (git diff "Target/$defaultBranch") {
-          git -c user.name=$UserName -c user.email=$UserEmail merge --strategy-option=theirs "Target/$defaultBranch"
-          FailOnError "Failed to merge for ${TargetRepo}:${TargetBranch}"
-          git -c user.name=$UserName -c user.email=$UserEmail rebase --strategy-option=theirs "Target/$defaultBranch"
-          FailOnError "Failed to rebase for ${TargetRepo}:${TargetBranch}"
-        }
+              $home_dir = $pwd
 
-        git push --force Target "${TargetBranch}:refs/heads/${TargetBranch}"
-        FailOnError "Failed to push to ${TargetRepo}:${TargetBranch}"
+              $SourceRepo = '${{ repo.key }}'
+              $SourceFolder = $SourceRepo -split "/" -join "-"
+              $SourceSyncFilePath = '${{repo.value.Path}}'
+              $SourceBranch = '${{ repo.value.Branch }}'
 
-        $FromPath = Join-Path $home_dir "$SourceFolder" "$SourceSyncFilePath"
-        $ToPath = Join-Path $home_dir "$TargetFolder" "$TargetSyncFilePath"
+              $pullRequestBranch = "Sync-from-$SourceFolder"
 
-        if (test-path $ToPath) {
-          Remove-Item "$ToPath" -Force -Recurse
-        }
-        
-        Copy-Item -Path "$FromPath" -Destination "$ToPath" -Recurse -Force
+              $TargetRepo = '${{ target.key }}'
+              $TargetFolder = $TargetRepo -split "/" -join "-"
+              $TargetSyncFilePath = '${{target.value.Path}}'
+              $TargetBranch = '${{ target.value.Branch }}'
 
-        $untrackkedFiles = git ls-files -o 
-        if ($untrackkedFiles) {
-          git add .
-          git commit -m "Add untracked files"
-          git push --force Target $($TargetBranch)
-          FailOnError "Failed to push to $($TargetRepo):$($TargetBranch)"
-        } else {
-          $diffResult = git diff "refs/remotes/Target/$($defaultBranch)"
-          if ($diffResult) {
-            git add .
-            git commit -m "Sync files from $SourceReo/$SourceBranch"
-            git push --force Target $($TargetBranch)
-            FailOnError "Failed to push to $($TargetRepo):$($TargetBranch)"
-          }
-        }
+              Function FailOnError([string]$ErrorMessage, $CleanUpScripts = 0) {
+                if ($LASTEXITCODE -ne 0) {
+                  Write-Host "#`#vso[task.logissue type=error]$ErrorMessage"
+                  if ($CleanUpScripts -ne 0) { Invoke-Command $CleanUpScripts }
+                  exit 1
+                }
+              }
 
-        $OwnerName = ($TargetRepo -split '/')[0] 
-        $pullRequests = Get-GitHubPullRequest `
-          -AccessToken ${{ parameters.GH_TOKEN }} `
-          -Uri "https://github.com/$($TargetRepo)" `
-          -State Open `
-          -Head "$($OwnerName):$($TargetBranch)" `
-          -Base "main" 
-        FailOnError "Get $($TargetRepo) pull request: $_"
+              if (-not (Test-Path $TargetFolder)) {
+                New-Item -Path $TargetFolder -ItemType Directory -Force
+                Set-Location $TargetFolder
+                git init
+                git remote add Target "https://${{parameters.GH_TOKEN}}@github.com/${TargetRepo}.git"
+              } else {
+                Set-Location $TargetFolder
+              }
 
-        if ($pullRequests.Count -ne 0) { 
-          echo "PR has been created at https://github.com/$($TargetRepo)/pull/$($pullRequests.number)"
-        } else {
-          $newPullRequest = New-GitHubPullRequest `
-            -AccessToken ${{ parameters.GH_TOKEN }} `
-            -Uri "https://github.com/$($TargetRepo)" `
-            -Head "$($OwnerName):$($TargetBranch)" `
-            -Base $($defaultBranch) `
-            -Title "test title2" `
-            -Body "test body2" `
-            -MaintainerCanModify `
-          FailOnError "create $($TargetBranch) pull request: $_"
+              if (!$TargetBranch) {
+                $defaultBranch = (git remote show Target | Out-String) -replace "(?ms).*HEAD branch: (\w+).*", '$1'
+                Write-Host "No target branch. Fetch default branch $defaultBranch."
+                $TargetBranch = $defaultBranch
+              }
 
-          echo "PR has been created at https://github.com/$($TargetRepo)/pull/$($newPullRequest.number)"
-        }
+              git fetch --all
+              FailOnError "Failed to fetch DefaultBranch ${defaultBranch}."
 
-        Set-PsDebug -Off
+              $isExistBranch = $(git branch --list --remotes "Target/$pullRequestBranch")
+              if ($isExistBranch) {
+                git checkout -b $pullRequestBranch "Target/$pullRequestBranch"
+              }
+              else {
+                git checkout -b $pullRequestBranch "Target/$TargetBranch"
+              }
 
-      displayName: Sync ${{ target.value.Path }} files from ${{ repo.key }} to ${{ target.key }}
-      continueOnError: true
+              if (git diff "Target/$TargetBranch") {
+                git -c user.name=$UserName -c user.email=$UserEmail merge --strategy-option=theirs "Target/$TargetBranch"
+                FailOnError "Failed to merge for ${TargetRepo}:${TargetBranch}"
+                git -c user.name=$UserName -c user.email=$UserEmail rebase --strategy-option=theirs "Target/$TargetBranch"
+                FailOnError "Failed to rebase for ${TargetRepo}:${TargetBranch}"
+              }
+
+              git push --force Target "${TargetBranch}:refs/heads/${TargetBranch}"
+              FailOnError "Failed to push to ${TargetRepo}:${TargetBranch}"
+
+              $FromPath = Join-Path $home_dir "$SourceFolder" "$SourceSyncFilePath"
+              $ToPath = Join-Path $home_dir "$TargetFolder" "$TargetSyncFilePath"
+
+              if (test-path $ToPath) {
+                Remove-Item "$ToPath" -Force -Recurse
+              }
+
+              Copy-Item -Path "$FromPath" -Destination "$ToPath" -Recurse -Force
+
+              $untrackkedFiles = git ls-files -o 
+              if ($untrackkedFiles) {
+                git add .
+                git commit -m "Add untracked files"
+                git push --force Target $($pullRequestBranch)
+                FailOnError "Failed to push to $($TargetRepo):$($pullRequestBranch)"
+              } else {
+                $diffResult = git diff "refs/remotes/Target/$($TargetBranch)"
+                if ($diffResult) {
+                  git add .
+                  git commit -m "Sync files from $SourceReo/$SourceBranch"
+                  git push --force Target $($pullRequestBranch)
+                  FailOnError "Failed to push to $($TargetRepo):$($pullRequestBranch)"
+                }
+              }
+
+              $OwnerName = ($TargetRepo -split '/')[0] 
+              $pullRequests = Get-GitHubPullRequest `
+                -AccessToken ${{ parameters.GH_TOKEN }} `
+                -Uri "https://github.com/$($TargetRepo)" `
+                -State Open `
+                -Head "$($OwnerName):$($pullRequestBranch)" `
+                -Base $($TargetBranch) `
+              FailOnError "Get $($TargetRepo) pull request: $_"
+
+              if ($pullRequests.Count -ne 0) { 
+                echo "PR has been created at https://github.com/$($TargetRepo)/pull/$($pullRequests.number)"
+              } else {
+                $newPullRequest = New-GitHubPullRequest `
+                  -AccessToken ${{ parameters.GH_TOKEN }} `
+                  -Uri "https://github.com/$($TargetRepo)" `
+                  -Head "$($OwnerName):$($pullRequestBranch)" `
+                  -Base $($TargetBranch) `
+                  -Title "test title2" `
+                  -Body "test body2" `
+                  -MaintainerCanModify `
+                FailOnError "create $($pullRequestBranch) pull request: $_"
+
+                echo "PR has been created at https://github.com/$($TargetRepo)/pull/$($newPullRequest.number)"
+              }
+
+              Set-PsDebug -Off
+
+            displayName: Sync ${{ target.value.Path }} files from ${{ repo.key }} to ${{ target.key }}
+            continueOnError: true
